import { EventCard } from "./EventCard"

const events = [
  {
    title: "Crime Scene Investigation",
    description: "Put your detective skills to the test in this thrilling crime scene investigation challenge.",
    time: "10:00 AM - 12:00 PM",
    place: "CR - 33",
    videoUrl: "https://www.youtube.com/live/q_JsgpiuY98?si=GkrEnp70QbssXf55",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹49",
    ranking: {
      first: "Team Sherlock",
      second: "CSI Masters",
      third: "Detective Squad",
    },
    date: "2023-09-15",
    eventHead: "Sanidha Panda",
    eventHeadContact: "9987201676",
    eventCoHead: "Siddesh Sharma",
    eventCoHeadContact: "9324419285",
  },
  {
    title: "Escape Room",
    description: "Work together to solve puzzles and escape before time runs out!",
    time: "11:00 AM - 1:00 PM",
    place: "CR -",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹0",
    ranking: {
      first: "Escape Artists",
      second: "Puzzle Breakers",
      third: "Time Benders",
    },
    date: "2023-09-16",
    eventHead: "Krisha Ebrahimpurkar",
    eventHeadContact: "9324292922",
    eventCoHead: "Ayaan Fakir",
    eventCoHeadContact: "9969558050",
  },
  {
    title: "AR Treasure Hunt",
    description: "Embark on a high-tech treasure hunt using augmented reality.",
    time: "2:00 PM - 4:00 PM",
    place: "College Building",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹250",
    ranking: {
      first: "Team Rocket",
      second: "Treasure Hunters",
      third: "AR Explorers",
    },
    date: "2023-09-17",
    eventHead: "Tanish Shah",
    eventHeadContact: "8291285782",
    eventCoHead: "Tanishq Gohil",
    eventCoHeadContact: "9076090728",
  },
  {
    title: "Giant Jenga",
    description: "Test your steady hands and strategy in this supersized version of the classic game.",
    time: "3:00 PM - 5:00 PM",
    place: "Cage",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹20",
    ranking: {
      first: "Jenga Masters",
      second: "Tower Builders",
      third: "Steady Hands",
    },
    date: "2023-09-18",
    eventHead: "Nikhil Gohil",
    eventHeadContact: "9372618528",
    eventCoHead: "Zain P",
    eventCoHeadContact: "9967712515",
  },
  {
    title: "Glow in the dark pickle ball",
    description: "Experience the fast-paced fun of pickleball with a luminous twist!",
    time: "7:00 PM - 9:00 PM",
    place: "ED Hall",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹50",
    ranking: {
      first: "Night Owls",
      second: "Glow Getters",
      third: "Pickleball Pros",
    },
    date: "2023-09-19",
    eventHead: "Harsh",
    eventHeadContact: "9372829908",
    eventCoHead: "Monarch",
    eventCoHeadContact: "8928244779",
  },
  {
    title: "Lazer Maze",
    description: "Navigate through a web of lasers in this Mission Impossible-style challenge.",
    time: "1:00 PM - 3:00 PM",
    place: "CR -",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹0",
    ranking: {
      first: "Laser Ninjas",
      second: "Maze Masters",
      third: "Mission Accomplished",
    },
    date: "2023-09-20",
    eventHead: "Nikhil E",
    eventHeadContact: "8260753244",
    eventCoHead: "Khushiya P",
    eventCoHeadContact: "8624046649",
  },
  {
    title: "VR Gaming",
    description: "Immerse yourself in virtual worlds and experience the future of gaming and simulation.",
    time: "11:00 AM - 7:00 PM",
    place: "Timezone(Foyer)",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹99",
    ranking: {
      first: "VR Voyagers",
      second: "Virtual Victors",
      third: "Reality Rebels",
    },
    date: "2023-10-01",
  },
  {
    title: "FIFA",
    description: "Show off your virtual football skills in this exciting FIFA tournament.",
    time: "6:00 PM - 10:00 PM",
    place: "Timezone(Foyer)",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹69",
    ranking: {
      first: "FIFA Fanatics",
      second: "Football Fury",
      third: "Goal Getters",
    },
    date: "2023-09-30",
  },
  {
    title: "Mortal Kombat",
    description: "Test your fighting game skills in this classic Mortal Kombat showdown.",
    time: "7:00 PM - 11:00 PM",
    place: "Timezone(Foyer)",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹49",
    ranking: {
      first: "Kombat Kings",
      second: "Fighting Force",
      third: "Mortal Masters",
    },
    date: "2023-10-02",
  },
  {
    title: "F1",
    description: "Race through virtual city streets in this exciting gaming event.",
    time: "5:00 PM - 8:00 PM",
    place: "Timezone(Foyer)",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹69",
    ranking: {
      first: "Street Racers",
      second: "City Slickers",
      third: "Speed Demons",
    },
    date: "2023-10-03",
  },
  {
    title: "1V1 PC's",
    description: "Compete in the ultimate 1V1 PC showdown!",
    time: "4:00 PM - 8:00 PM",
    place: "Timezone(Foyer)",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹49",
    ranking: {
      first: "Chicken Dinners",
      second: "BGMI Champs",
      third: "Elite Squad",
    },
    date: "2023-09-21",
  },
  {
    title: "Getting Over It",
    description: "Show off your tactical prowess in this Getting Over It tournament.",
    time: "5:00 PM - 9:00 PM",
    place: "Timezone(Foyer)",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹69",
    ranking: {
      first: "Valorant Veterans",
      second: "Tactical Titans",
      third: "Agent Aces",
    },
    date: "2023-09-22",
  },
  {
    title: "RC Car Race",
    description: "Design, build, and race your custom robots in this high-speed competition.",
    time: "2:00 PM - 4:00 PM",
    place: "Ground",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹100",
    ranking: {
      first: "Speed Demons",
      second: "Robo Racers",
      third: "Circuit Champions",
    },
    date: "2023-09-24",
  },
]

export function Events() {
  return (
    <div className="container mx-auto px-4 py-8 bg-gray-900">
      <h2 className="text-2xl font-bold mb-6 text-white">Events</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
        {events.map((event, index) => (
          <EventCard key={index} {...event} />
        ))}
      </div>
    </div>
  )
}

