import { EventCard } from "./EventCard";

const festName = "aurum";

const events = [
  {
    title: "F1 Racing",
    description: "Experience the thrill of high-speed racing in this F1 simulation.",
    time: "10th & 11th Feb",
    place: "Foyer",
    price: "₹70 per person",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/F1racing.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Rehan S.",
    eventHeadContact: "9321621747",
    eventCoHead: "Shreyans V.",
    eventCoHeadContact: "9930866499",
  },
  {
    title: "Mortal Kombat",
    description: "Fight your way to victory in this legendary fighting game.",
    time: "10th & 11th Feb",
    place: "Foyer",
    price: "₹50 per person",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/MortalKombat.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Rehan S.",
    eventHeadContact: "9321621747",
    eventCoHead: "Shreyans V.",
    eventCoHeadContact: "9930866499",
  },
  {
    title: "FIFA",
    description: "Show off your virtual football skills in this exciting FIFA tournament.",
    time: "10th & 11th Feb",
    place: "Foyer",
    price: "₹70 for 1, ₹100 for 2",
    videoUrl: "https://www.youtube.com/live/f1_race",    
    imageUrl: "/aurum/FIFA.webp",     
    ranking: {       
     first: "Speed Demons",       
     second: "Turbo Racers",       
     third: "Nitro Boosters",    
   },    
   date: "2025-02-10",
    eventHead: "Rehan S.",
    eventHeadContact: "9321621747",
    eventCoHead: "Shreyans V.",
    eventCoHeadContact: "9930866499",
  },
  {
    title: "PC Gaming (1v1)",
    description: "Compete head-to-head in thrilling PC games.",
    time: "10th & 11th Feb",
    place: "Foyer",
    price: "₹50 per person",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/PC(1vs1).webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Rehan S.",
    eventHeadContact: "9321621747",
    eventCoHead: "Shreyans V.",
    eventCoHeadContact: "9930866499",
  },
  {
    title: "Laser Maze",
    description: "Dodge lasers and complete the maze in record time!",
    time: "10th & 11th Feb",
    place: "GR 25",
    price: "₹70 solo, ₹120 duo",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/LaserMaze.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Nikhil E.",
    eventHeadContact: "8260753244",
    eventCoHead: "Khushiya P.",
    eventCoHeadContact: "8624046649",
  },
  {
    title: "Crime Scene Investigation",
    description: "Put your detective skills to the test in this thrilling crime scene investigation challenge.",
    time: "10th & 11th Feb",
    place: "CR-33",
    price: "₹50 per person or ₹200 per team (max 5)",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/CSI.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Sanidha P.",
    eventHeadContact: "9987201676",
    eventCoHead: "Siddhesh S.",
    eventCoHeadContact: "9324419285",
  },
  {
    title: "Glow in the Dark Pickle Ball",
    description: "A unique twist to pickleball with a glowing arena.",
    time: "10th & 11th Feb",
    place: "ED Hall, 7th Floor",
    price: "₹50 per person",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/GlowInTheDark.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Harsh",
    eventHeadContact: "9372829908",
    eventCoHead: "Monarch",
    eventCoHeadContact: "8928244779",
  },
  {
    title: "Giant Jenga",
    description: "Test your steady hands and strategy in this supersized version of the classic game.",
    time: "10th & 11th Feb",
    place: "Cage",
    price: "₹20",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/GiantJenga.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Nikhil G.",
    eventHeadContact: "9372618528",
    eventCoHead: "Zain P.",
    eventCoHeadContact: "9967712515",
  },
  {
    title: "Escape Room",
    description: "Work together to solve puzzles and escape before time runs out!",
    time: "10th & 11th Feb",
    place: "CR-53",
    price: "₹50 per person or ₹200 per team (max 5)",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/EscapeRoom.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Krisha E.",
    eventHeadContact: "9324292922",
    eventCoHead: "Ayaan F.",
    eventCoHeadContact: "9969558050",
  },
  {
    title: "AR Treasure Hunt",
    description: "Embark on a high-tech treasure hunt using augmented reality.",
    time: "10th & 11th Feb",
    place: "CR-14",
    price: "₹200 for 3-5 people",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/ArTeasureHunt.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Tanish S.",
    eventHeadContact: "8291285782",
    eventCoHead: "Tanishq G.",
    eventCoHeadContact: "9076090728",
  },
  {
    title: "VR Gaming",
    description: "Dive into immersive virtual reality experiences!",
    time: "10th & 11th Feb",
    place: "Foyer",
    price: "₹70 for 10 min",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/VR.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Sachin S.",
    eventHeadContact: "9136712581",
    eventCoHead: "Om",
    eventCoHeadContact: "7506936880",
  },
  {
    title: "Arcadia GameZone",
    description: "Dive into immersive virtual reality experiences!",
    time: "10th & 11th Feb",
    place: "Foyer",
    price: "₹70",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/ArcadiaGamezone.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Rehan S.",
    eventHeadContact: "9321621747",
    eventCoHead: "Sanjana S.",
    eventCoHeadContact: "9373897716",
  },
  {
    title: "Getting Over It",
    description: "Conquer the toughest platforming challenge in gaming history.",
    time: "10th & 11th Feb",
    place: "Foyer",
    price: "₹50 level-based",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/GettingOverit.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Rehan S.",
    eventHeadContact: "9321621747",
    eventCoHead: "Sanjana S.",
    eventCoHeadContact: "9373897716",
  },
  {
    title: "RC Car Racing",
    description: "Race remote-controlled cars in an adrenaline-packed event.",
    time: "10th & 11th Feb",
    place: "Foyer",
    price: "₹100 solo, ₹150 duo, ₹250 quad",
    videoUrl: "https://www.youtube.com/live/f1_race",    
     imageUrl: "/aurum/RcCarRacing.webp",     
     ranking: {       
      first: "Speed Demons",       
      second: "Turbo Racers",       
      third: "Nitro Boosters",    
    },    
    date: "2025-02-10",
    eventHead: "Sid",
    eventHeadContact: "9403144527",
    eventCoHead: "Sanjana S.",
    eventCoHeadContact: "9373897716",
  }
];

export function Events() {
  return (
    <div className="container mx-auto px-4 py-8 bg-gray-900 rounded-lg">
      <h2 className="text-2xl font-bold mb-6 text-white">Events</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
        {events.map((event, index) => (
          <EventCard key={index} {...event} festName={festName} />
        ))}
      </div>
    </div>
  );
}
