import { EventCard } from "./EventCard"

const events = [
  {
    title: "Crime Scene Investigation",
    description: "Put your detective skills to the test in this thrilling crime scene investigation challenge.",
    time: "10:00 AM - 12:00 PM",
    place: "Forensic Lab",
    videoUrl: "https://www.youtube.com/live/q_JsgpiuY98?si=GkrEnp70QbssXf55",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹200",
    ranking: {
      first: "Team Sherlock",
      second: "CSI Masters",
      third: "Detective Squad",
    },
    date: "2023-09-15",
  },
  {
    title: "Escape Room",
    description: "Work together to solve puzzles and escape before time runs out!",
    time: "11:00 AM - 1:00 PM",
    place: "Mystery Room",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹250",
    ranking: {
      first: "Escape Artists",
      second: "Puzzle Breakers",
      third: "Time Benders",
    },
    date: "2023-09-16",
  },
  {
    title: "AR Treasure Hunt",
    description: "Embark on a high-tech treasure hunt using augmented reality.",
    time: "2:00 PM - 4:00 PM",
    place: "Campus Grounds",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹150",
    ranking: {
      first: "Team Rocket",
      second: "Treasure Hunters",
      third: "AR Explorers",
    },
    date: "2023-09-17",
  },
  {
    title: "Giant Jenga",
    description: "Test your steady hands and strategy in this supersized version of the classic game.",
    time: "3:00 PM - 5:00 PM",
    place: "Main Quad",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹100",
    ranking: {
      first: "Jenga Masters",
      second: "Tower Builders",
      third: "Steady Hands",
    },
    date: "2023-09-18",
  },
  {
    title: "Glow-in-the-Dark Pickleball",
    description: "Experience the fast-paced fun of pickleball with a luminous twist!",
    time: "7:00 PM - 9:00 PM",
    place: "Sports Complex",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹180",
    ranking: {
      first: "Night Owls",
      second: "Glow Getters",
      third: "Pickleball Pros",
    },
    date: "2023-09-19",
  },
  {
    title: "Laser Maze",
    description: "Navigate through a web of lasers in this Mission Impossible-style challenge.",
    time: "1:00 PM - 3:00 PM",
    place: "Physics Lab",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹220",
    ranking: {
      first: "Laser Ninjas",
      second: "Maze Masters",
      third: "Mission Accomplished",
    },
    date: "2023-09-20",
  },
  {
    title: "BGMI Tournament",
    description: "Compete in the ultimate BGMI showdown!",
    time: "4:00 PM - 8:00 PM",
    place: "Gaming Arena",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹300",
    ranking: {
      first: "Chicken Dinners",
      second: "BGMI Champs",
      third: "Elite Squad",
    },
    date: "2023-09-21",
  },
  {
    title: "Valorant Championship",
    description: "Show off your tactical prowess in this Valorant tournament.",
    time: "5:00 PM - 9:00 PM",
    place: "E-Sports Center",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹300",
    ranking: {
      first: "Valorant Veterans",
      second: "Tactical Titans",
      third: "Agent Aces",
    },
    date: "2023-09-22",
  },
  {
    title: "Robo Sumo",
    description: "Build and battle with your sumo wrestling robots!",
    time: "11:00 AM - 1:00 PM",
    place: "Robotics Lab",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹250",
    ranking: {
      first: "Robo Rumble",
      second: "Sumo Stars",
      third: "Bot Brawlers",
    },
    date: "2023-09-23",
  },
  {
    title: "Robo Race",
    description: "Design, build, and race your custom robots in this high-speed competition.",
    time: "2:00 PM - 4:00 PM",
    place: "Racing Track",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹280",
    ranking: {
      first: "Speed Demons",
      second: "Robo Racers",
      third: "Circuit Champions",
    },
    date: "2023-09-24",
  },
  {
    title: "Cozmo Clench",
    description: "Program Cozmo robots to complete challenging tasks in this AI-focused event.",
    time: "3:00 PM - 5:00 PM",
    place: "AI Lab",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹200",
    ranking: {
      first: "AI Aces",
      second: "Cozmo Commanders",
      third: "Coding Crew",
    },
    date: "2023-09-25",
  },
  {
    title: "Technokagaz",
    description: "Showcase your paper circuit designs in this innovative tech-meets-craft event.",
    time: "10:00 AM - 12:00 PM",
    place: "Design Studio",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹150",
    ranking: {
      first: "Circuit Wizards",
      second: "Paper Pros",
      third: "Technocrats",
    },
    date: "2023-09-26",
  },
  {
    title: "Tech Expo",
    description: "Explore cutting-edge technology demonstrations from industry leaders and student innovators.",
    time: "9:00 AM - 5:00 PM",
    place: "Exhibition Hall",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "Free",
    ranking: {
      first: "Innovation Inc.",
      second: "Tech Titans",
      third: "Future Forward",
    },
    date: "2023-09-27",
  },
  {
    title: "Code of Duty",
    description: "Test your coding skills in this fast-paced programming challenge.",
    time: "1:00 PM - 3:00 PM",
    place: "Computer Lab",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹200",
    ranking: {
      first: "Coding Ninjas",
      second: "Debug Masters",
      third: "Algorithm Aces",
    },
    date: "2023-09-28",
  },
  {
    title: "Cybersecurity Challenge",
    description: "Defend against simulated cyber attacks in this intense security competition.",
    time: "4:00 PM - 6:00 PM",
    place: "Security Operations Center",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹250",
    ranking: {
      first: "Cyber Warriors",
      second: "Security Squad",
      third: "Firewall Force",
    },
    date: "2023-09-29",
  },
  {
    title: "FIFA Tournament",
    description: "Show off your virtual football skills in this exciting FIFA tournament.",
    time: "6:00 PM - 10:00 PM",
    place: "Gaming Lounge",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹200",
    ranking: {
      first: "FIFA Fanatics",
      second: "Football Fury",
      third: "Goal Getters",
    },
    date: "2023-09-30",
  },
  {
    title: "VR Room",
    description: "Immerse yourself in virtual worlds and experience the future of gaming and simulation.",
    time: "11:00 AM - 7:00 PM",
    place: "VR Lab",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹300",
    ranking: {
      first: "VR Voyagers",
      second: "Virtual Victors",
      third: "Reality Rebels",
    },
    date: "2023-10-01",
  },
  {
    title: "Mortal Kombat Tournament",
    description: "Test your fighting game skills in this classic Mortal Kombat showdown.",
    time: "7:00 PM - 11:00 PM",
    place: "Arcade Center",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹180",
    ranking: {
      first: "Kombat Kings",
      second: "Fighting Force",
      third: "Mortal Masters",
    },
    date: "2023-10-02",
  },
  {
    title: "Midtown Madness",
    description: "Race through virtual city streets in this exciting gaming event.",
    time: "5:00 PM - 8:00 PM",
    place: "Simulation Room",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    imageUrl: "/placeholder.svg?height=200&width=300",
    price: "₹220",
    ranking: {
      first: "Street Racers",
      second: "City Slickers",
      third: "Speed Demons",
    },
    date: "2023-10-03",
  },
]

export function Events() {
  return (
    <div className="container mx-auto px-4 py-8 bg-gray-900">
      <h2 className="text-2xl font-bold mb-6 text-white">Events</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
        {events.map((event, index) => (
          <EventCard key={index} {...event} />
        ))}
      </div>
    </div>
  )
}

